address:              'smtp.gmail.com'
port:                 '587'
domain:               'gmail.com'
user_name:            '__user_name__@gmail.com'
password:             '__password__'
authentication:       'login'
enable_starttls_auto: 'true'
delivery_method:      'smtp'
from:                 '__user_name__@gmail.com'
to:                   '__to__@gmail.com'