development:
# enable dict crc if you want to enable single letter searches
#  dict: crc
  morphology: stem_ru
  #expand_keywords: true
  blend_chars: 0..9
  index_exact_words: true
  min_infix_len: 2
  charset_table: A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+451, U+451
production:
# enable dict crc if you want to enable single letter searches
# dict: crc
  morphology: stem_ru
  #expand_keywords: true
  blend_chars: 0..9
  index_exact_words: true
  min_infix_len: 2
  charset_table: A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+451, U+451
